apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-console/master/app-kubernetes/src/main/fabric8/icon.svg
  labels:
    expose: "true"
    group: io.fabric8.apps
    project: console
    provider: fabric8
    version: 2.2.182
  name: fabric8
  namespace: default
spec:
  replicas: 1
  selector:
    expose: "true"
    group: io.fabric8.apps
    project: console
    provider: fabric8
  template:
    metadata:
      labels:
        expose: "true"
        group: io.fabric8.apps
        project: console
        provider: fabric8
        version: 2.2.182
    spec:
      containers:
      - env:
        - name: OAUTH_AUTHORIZE_PORT
          value: "8443"
        - name: OAUTH_AUTHORIZE_URI
          value: https://10.0.2.15:8443/oauth/authorize
        - name: GOOGLE_OAUTH_AUTHENTICATION_URI
          value: https://accounts.google.com/o/oauth2/auth
        - name: GOOGLE_OAUTH_CLIENT_SECRET
        - name: OAUTH_PROVIDER
          value: openshift
        - name: GOOGLE_OAUTH_REDIRECT_URI
          value: https://fabric8.default.10.64.33.91.xip.io
        - name: GOOGLE_OAUTH_TOKEN_URL
          value: https://www.googleapis.com/oauth2/v3/token
        - name: GOOGLE_OAUTH_SCOPE
          value: profile
        - name: GITHUB_OAUTH_CLIENT_SECRET
        - name: GOOGLE_OAUTH_CLIENT_ID
        - name: OAUTH_CLIENT_ID
          value: fabric8
        - name: GITHUB_OAUTH_CLIENT_ID
        - name: HAWTIO_BRANDING_PLUGIN
          value: fabric8-branding
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: tangfeixiong/fabric8-console:zhs-latest
        imagePullPolicy: IfNotPresent
        name: fabric8-container
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: "0"
            memory: "0"
          requests:
            cpu: "0"
            memory: "0"
        securityContext: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  fullyLabeledReplicas: 1
  observedGeneration: 1
  replicas: 1
